Cart Page done
vanshitamoolchandani/DogsHut-Neog pull request #4
Opened 2022-02-18 19:16 UTC by vanshitamoolchandani

Cart page gives the checkout option and similar products.

2022-02-18 19:24 UTC, sri-rishi approved these changes
Looks good to me, can be merged

2022-02-18 21:15 UTC, git-0r requested changes

2022-02-18 21:15 UTC, git-0r commented on Pages/Cart/styles.css
> +@import url('/root.css');
![review1](https://user-images.githubusercontent.com/68228131/154761004-0211dee7-36af-4667-8f64-69195a8f58d7.png)

one css file request is failing.

2022-02-18 21:15 UTC, git-0r commented on Pages/Cart/index.html
> +                <li>Caree&#8377/li>
list tag not closed properly.

2022-02-18 21:15 UTC, git-0r commented on Pages/Cart/index.html
> +        <h4>Created by Vanshita Moolchandani</h4>
![review2](https://user-images.githubusercontent.com/68228131/154761596-50307bd1-2bac-40b3-b0a2-8d039603ad96.png)

you can remove those blue lines by using text-decoration: "none" on links.

2022-02-18 21:15 UTC, git-0r commented on Pages/Cart/index.html
> +            <a href="/Pages/Wishlist/index.html">
cart icon is connected to wishlist page.

2022-02-19 03:09 UTC, iprankurpandey commented
looks good , input box will be more attractive if you can give some style

2022-02-19 03:09 UTC, prankurpandeyy approved these changes

2022-02-19 07:56 UTC, merged